### ISSUE TITLE
Path confusion

### ISSUE THREAD

**Issue by saavikford** [McFACTS/McFACTS#3]
Hi, adding this issue: Harrison cloned this repo but could not get his python to read this setup file, because it was looking for a Sedona setup file (same naming convention) instead, due to something in his python path variable. He solved the problem by commenting out the line in his .bashrc(?) file, but for someone who actually wants to be able to run Sedona (he's not using it anymore) that is not a good solution... so we'll need to figure that one out and fix it more generically. This occurred even when he was using the correct conda environment.

**Comment by xevra** [comment]
Does this still occur when using pip to install the package? @cookhe

**Comment by saavikford** [comment]
Fixed, I think!
